# Generated by Django 5.1.3 on 2024-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledgesalawat',
            name='amount',
        ),
        migrations.AddField(
            model_name='pledgesalawat',
            name='pledge_count',
            field=models.IntegerField(default=0),
        ),
    ]
