# Generated by Django 5.1.3 on 2024-11-23 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salawat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salawat_title', models.CharField(max_length=255)),
                ('salawat_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salawat',
                'verbose_name_plural': 'Salawat',
            },
        ),
        migrations.CreateModel(
            name='SalawatAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salawat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salawat.salawat')),
            ],
            options={
                'verbose_name': 'Salawat Audio',
                'verbose_name_plural': 'Salawat Audios',
            },
        ),
        migrations.CreateModel(
            name='SalawatTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=1000)),
                ('salawat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salawat.salawat')),
            ],
            options={
                'verbose_name': 'Salawat Translation',
                'verbose_name_plural': 'Salawat Translations',
            },
        ),
    ]
